# Generated by Django 4.0.5 on 2022-10-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
