# Generated by Django 4.0.5 on 2022-09-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
