# Generated by Django 4.0.5 on 2022-10-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task4_app', '0008_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='task4_app.group'),
        ),
    ]
