# Generated by Django 4.0.5 on 2022-10-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4_app', '0009_user_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group_name',
        ),
    ]
