# Generated by Django 4.0.5 on 2022-10-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task4_app', '0010_rename_group_id_user_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_name', to='task4_app.group'),
        ),
    ]
